// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/drafts": {
            "get": {
                "description": "Get paginated editorial copy drafts with optional status and style ID filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drafts"
                ],
                "summary": "List drafts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by draft status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by product style ID",
                        "name": "style_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DraftListResult"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIError"
                        }
                    }
                }
            }
        },
        "/drafts/generate": {
            "post": {
                "description": "Call the AI core to generate copy variants for a product, then save as drafts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drafts"
                ],
                "summary": "Generate editorial copy",
                "parameters": [
                    {
                        "description": "Generate request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GenerateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIError"
                        }
                    }
                }
            }
        },
        "/drafts/{id}": {
            "get": {
                "description": "Get a single editorial draft by its numeric ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drafts"
                ],
                "summary": "Get draft",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Draft ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Draft"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIError"
                        }
                    }
                }
            },
            "put": {
                "description": "Update the headline and body of an existing editorial draft",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drafts"
                ],
                "summary": "Update draft",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Draft ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated content",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateDraftRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Draft"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIError"
                        }
                    }
                }
            }
        },
        "/drafts/{id}/approve": {
            "post": {
                "description": "Transition a draft to the approved state",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drafts"
                ],
                "summary": "Approve draft",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Draft ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reviewer information",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.TransitionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Draft"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIError"
                        }
                    }
                }
            }
        },
        "/drafts/{id}/archive": {
            "post": {
                "description": "Move a draft to the archived state",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drafts"
                ],
                "summary": "Archive draft",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Draft ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIError"
                        }
                    }
                }
            }
        },
        "/drafts/{id}/publish": {
            "post": {
                "description": "Transition a draft to published and push the editorial copy to the catalog service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drafts"
                ],
                "summary": "Publish draft",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Draft ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Publisher information",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.TransitionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Draft"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "middleware.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.Attribution": {
            "type": "string",
            "enum": [
                "fashion-office",
                "buyer",
                "stylist",
                "customer-loved"
            ],
            "x-enum-varnames": [
                "AttrFashionOffice",
                "AttrBuyer",
                "AttrStylist",
                "AttrCustomerLoved"
            ]
        },
        "models.Draft": {
            "type": "object",
            "properties": {
                "attribution": {
                    "$ref": "#/definitions/models.Attribution"
                },
                "body": {
                    "type": "string"
                },
                "brand": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "generated_by": {
                    "description": "\"ai\" | \"human\"",
                    "type": "string"
                },
                "headline": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "price_range": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "published_by": {
                    "type": "string"
                },
                "reviewed_by": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.DraftStatus"
                },
                "style_id": {
                    "type": "string"
                },
                "themes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tone_notes": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.DraftListResult": {
            "type": "object",
            "properties": {
                "drafts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Draft"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "models.DraftStatus": {
            "type": "string",
            "enum": [
                "draft",
                "approved",
                "published",
                "archived"
            ],
            "x-enum-varnames": [
                "StatusDraft",
                "StatusApproved",
                "StatusPublished",
                "StatusArchived"
            ]
        },
        "models.GenerateRequest": {
            "type": "object",
            "properties": {
                "attribution": {
                    "$ref": "#/definitions/models.Attribution"
                },
                "feedback": {
                    "type": "string"
                },
                "max_words": {
                    "type": "integer"
                },
                "num_variants": {
                    "type": "integer"
                },
                "previous_body": {
                    "type": "string"
                },
                "previous_headline": {
                    "type": "string"
                },
                "price_range": {
                    "type": "string"
                },
                "style_id": {
                    "type": "string"
                },
                "themes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.TransitionRequest": {
            "type": "object",
            "properties": {
                "note": {
                    "type": "string"
                },
                "published_by": {
                    "type": "string"
                },
                "reviewed_by": {
                    "type": "string"
                }
            }
        },
        "models.UpdateDraftRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "headline": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8089",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Editorial Service API",
	Description:      "AI-driven editorial copy generation and draft management",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
